source "https://rubygems.org"

gem "rails", "4.2.6"
gem "sass-rails", "~> 5.0"
gem "bootstrap-sass"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "devise"
gem "kaminari"
gem "kaminari-bootstrap", "~> 3.0.1"
gem "config"
gem "cancancan"
gem "reform"
gem "reform-rails"
gem "public_activity"
gem "sidekiq"
gem "ransack"
gem "delayed_job_active_record"

group :development, :test do
  gem "byebug"
  gem "sqlite3"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "faker"
end
